version: "3.9"

services:
  api:
    container_name: api
    build: ./php/api
    volumes:
      - ./php/api:/var/www/project
      - vendor:/var/www/project/vendor

  client:
    container_name: client
    build: ./js/client
    volumes:
      - ./js/client:/var/www/project
      - node_modules:/var/www/project/node_modules
    tty: true
    command: npm run dev

  db:
    container_name: db
    env_file: .env
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    volumes:
      - ./mysql/data:/var/lib/mysql

  web:
    container_name: web
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - api

volumes:
  node_modules:
  vendor:
